### ISSUE TITLE
У меня брата распидорасило из за конфига вим

### ISSUE THREAD

**Issue by Mr0maks** [rasongame/dots#1]

**Comment by rasongame** [comment]
Вытащи руки из жопы, мудак

**Comment by Mr0maks** [comment]
> Вытащи руки из жопы, мудак

У брата рук нету

**Comment by rasongame** [comment]
> > Вытащи руки из жопы, мудак
> 
> У брата рук нету

Эт печально, не переживай, люди и без рук могут компьютером пользоватся

**Comment by Mr0maks** [comment]
> > > Вытащи руки из жопы, мудак
> > 
> > 
> > У брата рук нету
> 
> Эт печально, не переживай, люди и без рук могут компьютером пользоватся

А ты пробовал ?
